export { Hero } from './home-hero'
export { HomeContent } from './home-content'
export { StatsSection } from './stats-section'
export { ProjectsCarousel } from './projects-section'
export { Partners } from './partners-section'
export { PartnersContent } from './partners-content'
export { TestimonialsSection } from './testimonials-section'
