services:
  db-dev:
    image: docker.io/library/postgres:17-alpine
    container_name: ong_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ong_pgdata_dev:/var/lib/postgresql/data

volumes:
  ong_pgdata_dev:
